# use "~" for path to user folder
default:
  --path: ~\Documents\MangaDex
  --save-as: pdf-volume
  -lang: en
  -sc:
  -ec:

custom:
  --path: dl
  --save-as: pdf-volume
  -lang: en
  -sc: "0"
  -ec: "1"
